# Generated by Django 5.0.6 on 2024-05-31 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_is_deleted_department_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_deleted',
        ),
    ]
