# Generated by Django 5.0.6 on 2024-05-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_company_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_deleted',
        ),
    ]
