# Generated by Django 5.0.6 on 2024-06-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_address_is_deleted_employee_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
