# Generated by Django 5.0.6 on 2024-06-02 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_rename_title_stage_name_stage_fulfilled_next_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
