# Generated by Django 5.0.6 on 2024-06-02 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='fulfilled_next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fulfilled_next_step', to='employees.stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='rejected_next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_next_step', to='employees.stage'),
        ),
    ]
